Info-q/src/Entity/Usr.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsrRepository")
 */
class Usr
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $ci_usr;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_usr;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email_usr;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Complain", mappedBy="ci_usr")
     */
    private $complains;

    public function __construct()
    {
        $this->complains = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCiUsr(): ?int
    {
        return $this->ci_usr;
    }

    public function setCiUsr(int $ci_usr): self
    {
        $this->ci_usr = $ci_usr;

        return $this;
    }

    public function getNameUsr(): ?string
    {
        return $this->name_usr;
    }

    public function setNameUsr(string $name_usr): self
    {
        $this->name_usr = $name_usr;

        return $this;
    }

    public function getEmailUsr(): ?string
    {
        return $this->email_usr;
    }

    public function setEmailUsr(string $email_usr): self
    {
        $this->email_usr = $email_usr;

        return $this;
    }

    /**
     * @return Collection|Complain[]
     */
    public function getComplains(): Collection
    {
        return $this->complains;
    }

    public function addComplain(Complain $complain): self
    {
        if (!$this->complains->contains($complain)) {
            $this->complains[] = $complain;
            $complain->setCiUsr($this);
        }

        return $this;
    }

    public function removeComplain(Complain $complain): self
    {
        if ($this->complains->contains($complain)) {
            $this->complains->removeElement($complain);
            // set the owning side to null (unless already changed)
            if ($complain->getCiUsr() === $this) {
                $complain->setCiUsr(null);
            }
        }

        return $this;
    }
}

Info-q/src/Form/UsrType.php
<?php

namespace App\Form;

use App\Entity\Usr;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UsrType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('ci_usr')
            ->add('name_usr')
            ->add('email_usr')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Usr::class,
        ]);
    }
}

Info-q/src/Controller/UsrController.php
<?php

namespace App\Controller;

use App\Entity\Usr;
use App\Form\UsrType;
use App\Repository\UsrRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/usr")
 */
class UsrController extends AbstractController
{
    /**
     * @Route("/", name="usr_index", methods={"GET"})
     */
    public function index(UsrRepository $usrRepository): Response
    {
        return $this->render('usr/index.html.twig', [
            'usrs' => $usrRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="usr_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $usr = new Usr();
        $form = $this->createForm(UsrType::class, $usr);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($usr);
            $entityManager->flush();

            return $this->redirectToRoute('usr_index');
        }

        return $this->render('usr/new.html.twig', [
            'usr' => $usr,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="usr_show", methods={"GET"})
     */
    public function show(Usr $usr): Response
    {
        return $this->render('usr/show.html.twig', [
            'usr' => $usr,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="usr_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Usr $usr): Response
    {
        $form = $this->createForm(UsrType::class, $usr);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('usr_index');
        }

        return $this->render('usr/edit.html.twig', [
            'usr' => $usr,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="usr_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Usr $usr): Response
    {
        if ($this->isCsrfTokenValid('delete'.$usr->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($usr);
            $entityManager->flush();
        }

        return $this->redirectToRoute('usr_index');
    }
}

Info-q/templates/usr/_delete_form.html.twig
<form method="post" action="{{ path('usr_delete', {'id': usr.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ usr.id) }}">
    <button class="btn">Delete</button>
</form>

Info-q/templates/usr/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Info-q/templates/usr/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Usr{% endblock %}

{% block body %}
    <h1>Edit Usr</h1>

    {{ include('usr/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('usr_index') }}">back to list</a>

    {{ include('usr/_delete_form.html.twig') }}
{% endblock %}

Info-q/templates/usr/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usr index{% endblock %}

{% block body %}
    <h1>Usr index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Ci_usr</th>
                <th>Name_usr</th>
                <th>Email_usr</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for usr in usrs %}
            <tr>
                <td>{{ usr.id }}</td>
                <td>{{ usr.ciUsr }}</td>
                <td>{{ usr.nameUsr }}</td>
                <td>{{ usr.emailUsr }}</td>
                <td>
                    <a href="{{ path('usr_show', {'id': usr.id}) }}">show</a>
                    <a href="{{ path('usr_edit', {'id': usr.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('usr_new') }}">Create new</a>
{% endblock %}

Info-q/templates/usr/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Usr{% endblock %}

{% block body %}
    <h1>Create new Usr</h1>

    {{ include('usr/_form.html.twig') }}

    <a href="{{ path('usr_index') }}">back to list</a>
{% endblock %}

Info-q/templates/usr/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usr{% endblock %}

{% block body %}
    <h1>Usr</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ usr.id }}</td>
            </tr>
            <tr>
                <th>Ci_usr</th>
                <td>{{ usr.ciUsr }}</td>
            </tr>
            <tr>
                <th>Name_usr</th>
                <td>{{ usr.nameUsr }}</td>
            </tr>
            <tr>
                <th>Email_usr</th>
                <td>{{ usr.emailUsr }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('usr_index') }}">back to list</a>

    <a href="{{ path('usr_edit', {'id': usr.id}) }}">edit</a>

    {{ include('usr/_delete_form.html.twig') }}
{% endblock %}