Info-q/src/Entity/Unit.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UnitRepository")
 */
class Unit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_uni;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_uni;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $route;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Complain", inversedBy="number_uni")
     */
    private $complain;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Station", inversedBy="units")
     */
    private $id_sta;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumberUni(): ?int
    {
        return $this->number_uni;
    }

    public function setNumberUni(int $number_uni): self
    {
        $this->number_uni = $number_uni;

        return $this;
    }

    public function getTypeUni(): ?string
    {
        return $this->type_uni;
    }

    public function setTypeUni(string $type_uni): self
    {
        $this->type_uni = $type_uni;

        return $this;
    }

    public function getRoute(): ?string
    {
        return $this->route;
    }

    public function setRoute(string $route): self
    {
        $this->route = $route;

        return $this;
    }

    public function getComplain(): ?Complain
    {
        return $this->complain;
    }

    public function setComplain(?Complain $complain): self
    {
        $this->complain = $complain;

        return $this;
    }

    public function getIdSta(): ?Station
    {
        return $this->id_sta;
    }

    public function setIdSta(?Station $id_sta): self
    {
        $this->id_sta = $id_sta;

        return $this;
    }
}

Info-q/src/Form/UnitType.php
<?php

namespace App\Form;

use App\Entity\Unit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UnitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('number_uni')
            ->add('type_uni')
            ->add('route')
            ->add('complain')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Unit::class,
        ]);
    }
}

Info-q/src/Controller/UnitController.php
<?php

namespace App\Controller;

use App\Entity\Unit;
use App\Form\UnitType;
use App\Repository\UnitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/unit")
 */
class UnitController extends AbstractController
{
    /**
     * @Route("/", name="unit_index", methods={"GET"})
     */
    public function index(UnitRepository $unitRepository): Response
    {
        return $this->render('unit/index.html.twig', [
            'units' => $unitRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="unit_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $unit = new Unit();
        $form = $this->createForm(UnitType::class, $unit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($unit);
            $entityManager->flush();

            return $this->redirectToRoute('unit_index');
        }

        return $this->render('unit/new.html.twig', [
            'unit' => $unit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="unit_show", methods={"GET"})
     */
    public function show(Unit $unit): Response
    {
        return $this->render('unit/show.html.twig', [
            'unit' => $unit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="unit_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Unit $unit): Response
    {
        $form = $this->createForm(UnitType::class, $unit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('unit_index');
        }

        return $this->render('unit/edit.html.twig', [
            'unit' => $unit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="unit_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Unit $unit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$unit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($unit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('unit_index');
    }
}

Info-q/templates/unit/_delete_form.html.twig
<form method="post" action="{{ path('unit_delete', {'id': unit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ unit.id) }}">
    <button class="btn">Delete</button>
</form>

Info-q/templates/unit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Info-q/templates/unit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Unit{% endblock %}

{% block body %}
    <h1>Edit Unit</h1>

    {{ include('unit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('unit_index') }}">back to list</a>

    {{ include('unit/_delete_form.html.twig') }}
{% endblock %}

Info-q/templates/unit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Unit index{% endblock %}

{% block body %}
    <h1>Unit index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Number_uni</th>
                <th>Type_uni</th>
                <th>Route</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for unit in units %}
            <tr>
                <td>{{ unit.id }}</td>
                <td>{{ unit.numberUni }}</td>
                <td>{{ unit.typeUni }}</td>
                <td>{{ unit.route }}</td>
                <td>
                    <a href="{{ path('unit_show', {'id': unit.id}) }}">show</a>
                    <a href="{{ path('unit_edit', {'id': unit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('unit_new') }}">Create new</a>
{% endblock %}

Info-q/templates/unit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Unit{% endblock %}

{% block body %}
    <h1>Create new Unit</h1>

    {{ include('unit/_form.html.twig') }}

    <a href="{{ path('unit_index') }}">back to list</a>
{% endblock %}

Info-q/templates/unit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Unit{% endblock %}

{% block body %}
    <h1>Unit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ unit.id }}</td>
            </tr>
            <tr>
                <th>Number_uni</th>
                <td>{{ unit.numberUni }}</td>
            </tr>
            <tr>
                <th>Type_uni</th>
                <td>{{ unit.typeUni }}</td>
            </tr>
            <tr>
                <th>Route</th>
                <td>{{ unit.route }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('unit_index') }}">back to list</a>

    <a href="{{ path('unit_edit', {'id': unit.id}) }}">edit</a>

    {{ include('unit/_delete_form.html.twig') }}
{% endblock %}