Info-q/src/Entity/Station.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StationRepository")
 */
class Station
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_sta;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_sta;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address_sta;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Unit", mappedBy="id_sta")
     */
    private $units;

    public function __construct()
    {
        $this->units = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdSta(): ?int
    {
        return $this->id_sta;
    }

    public function setIdSta(int $id_sta): self
    {
        $this->id_sta = $id_sta;

        return $this;
    }

    public function getNameSta(): ?string
    {
        return $this->name_sta;
    }

    public function setNameSta(string $name_sta): self
    {
        $this->name_sta = $name_sta;

        return $this;
    }

    public function getAddressSta(): ?string
    {
        return $this->address_sta;
    }

    public function setAddressSta(string $address_sta): self
    {
        $this->address_sta = $address_sta;

        return $this;
    }

    /**
     * @return Collection|Unit[]
     */
    public function getUnits(): Collection
    {
        return $this->units;
    }

    public function addUnit(Unit $unit): self
    {
        if (!$this->units->contains($unit)) {
            $this->units[] = $unit;
            $unit->setIdSta($this);
        }

        return $this;
    }

    public function removeUnit(Unit $unit): self
    {
        if ($this->units->contains($unit)) {
            $this->units->removeElement($unit);
            // set the owning side to null (unless already changed)
            if ($unit->getIdSta() === $this) {
                $unit->setIdSta(null);
            }
        }

        return $this;
    }
}

Info-q/src/Form/StationType.php
<?php

namespace App\Form;

use App\Entity\Station;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id_sta')
            ->add('name_sta')
            ->add('address_sta')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Station::class,
        ]);
    }
}

Info-q/src/Controller/StationController.php
<?php

namespace App\Controller;

use App\Entity\Station;
use App\Form\StationType;
use App\Repository\StationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/station")
 */
class StationController extends AbstractController
{
    /**
     * @Route("/", name="station_index", methods={"GET"})
     */
    public function index(StationRepository $stationRepository): Response
    {
        return $this->render('station/index.html.twig', [
            'stations' => $stationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="station_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $station = new Station();
        $form = $this->createForm(StationType::class, $station);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($station);
            $entityManager->flush();

            return $this->redirectToRoute('station_index');
        }

        return $this->render('station/new.html.twig', [
            'station' => $station,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="station_show", methods={"GET"})
     */
    public function show(Station $station): Response
    {
        return $this->render('station/show.html.twig', [
            'station' => $station,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="station_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Station $station): Response
    {
        $form = $this->createForm(StationType::class, $station);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('station_index');
        }

        return $this->render('station/edit.html.twig', [
            'station' => $station,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="station_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Station $station): Response
    {
        if ($this->isCsrfTokenValid('delete'.$station->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($station);
            $entityManager->flush();
        }

        return $this->redirectToRoute('station_index');
    }
}

Info-q/templates/station/_delete_form.html.twig
<form method="post" action="{{ path('station_delete', {'id': station.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ station.id) }}">
    <button class="btn">Delete</button>
</form>

Info-q/templates/station/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Info-q/templates/station/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Station{% endblock %}

{% block body %}
    <h1>Edit Station</h1>

    {{ include('station/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('station_index') }}">back to list</a>

    {{ include('station/_delete_form.html.twig') }}
{% endblock %}

Info-q/templates/station/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Station index{% endblock %}

{% block body %}
    <h1>Station index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_sta</th>
                <th>Name_sta</th>
                <th>Address_sta</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for station in stations %}
            <tr>
                <td>{{ station.id }}</td>
                <td>{{ station.idSta }}</td>
                <td>{{ station.nameSta }}</td>
                <td>{{ station.addressSta }}</td>
                <td>
                    <a href="{{ path('station_show', {'id': station.id}) }}">show</a>
                    <a href="{{ path('station_edit', {'id': station.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('station_new') }}">Create new</a>
{% endblock %}

Info-q/templates/station/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Station{% endblock %}

{% block body %}
    <h1>Create new Station</h1>

    {{ include('station/_form.html.twig') }}

    <a href="{{ path('station_index') }}">back to list</a>
{% endblock %}

Info-q/templates/station/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Station{% endblock %}

{% block body %}
    <h1>Station</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ station.id }}</td>
            </tr>
            <tr>
                <th>Id_sta</th>
                <td>{{ station.idSta }}</td>
            </tr>
            <tr>
                <th>Name_sta</th>
                <td>{{ station.nameSta }}</td>
            </tr>
            <tr>
                <th>Address_sta</th>
                <td>{{ station.addressSta }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('station_index') }}">back to list</a>

    <a href="{{ path('station_edit', {'id': station.id}) }}">edit</a>

    {{ include('station/_delete_form.html.twig') }}
{% endblock %}